### PR TITLE
added support for sublimetext (stdin/filename handling)

### PR DESCRIPTION
**Pull request by iham**

### CODE REVIEW

**Comment by iham** [comment]
please give me some help about how to write tests for stdin ...

**Comment by gforcada** [comment]
@iham good question, do you rely on other flake8 plugins that do have stdin support? Maybe on flake8 itself or other "bigger" flake8 plugins there are tests for that.

You probably can fake that (just from the top of my head) with pushing data on sys.stdin? A quick search leads to this: http://stackoverflow.com/questions/6271947/how-can-i-simulate-input-to-stdin-for-pyunit

**Comment by gforcada** [comment]
@iham and btw. thanks a lot for taking care of the stdin issue on all my flake8 plugins!! Much appreciated! 🙇

**Comment by iham** [comment]
i feel like opening the box of pandora on the testing topic :( thats way beyond my skills of programming right now

i managed to fix another problem but have no clue how to use travis and how to re-increase coverage (testing against stdin)

**Comment by gforcada** [comment]
#5 builds on top of this one.

**Pull request closed without merging**
